version: "3.8"
services:  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: elimasrojas@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    